import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { clsx } from '@/common/utils/clsx';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={clsx(
					inter.className,
					`max-w-4xl mx-auto mt-12 w-full`
				)}
			>
				<div className="mb-4">
					<Link href="/">Home</Link>
				</div>
				{children}
			</body>
		</html>
	);
}
